#!/bin/ksh
set -e

v=3.3.1

# /etc/libre/ to avoid conflict with distro's openssl

wget -c https://ftp.openbsd.org/pub/OpenBSD/LibreSSL/libressl-$v.tar.gz
wget -c https://ftp.openbsd.org/pub/OpenBSD/LibreSSL/libressl-$v.tar.gz.asc
gpg --recv-key 4B708F96
gpg --verify libressl-$v.tar.gz.asc
[[ ! -d libressl-$v/ ]] && tar xzf libressl-$v.tar.gz
cd libressl-$v/
patch -p0 < ../libressl-3.3.1.patch
./configure --enable-nc --with-openssldir=/etc/libre && echo CONFIGURED
#make clean >/dev/null && echo CLEAN
make && echo BUILT
make install && echo INSTALLED
#openssl: error while loading shared libraries: libssl.so.48: cannot open shared object file: No such file or directory
grep /usr/local/lib /etc/ld.so.conf
ldconfig
cd ../

ls -ldhF /etc/libre/
ls -alhF /etc/libre/

#gone
#--disable-nls

# https://github.com/libressl-portable/portable/tags
#./autogen.sh
#
# https://ftp.openbsd.org/pub/OpenBSD/LibreSSL/
#
# http://www.edwardhk.com/os/linux/libressl-setup/
# https://obvi.us/crypto/libressl/
# https://askubuntu.com/questions/708057/how-to-fix-undefined-reference-to-to-sslv3-client-method-during-curl-custom

